name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup SSH key
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Install cloudflared
      - name: Install cloudflared
        run: |
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb
          sudo apt-get install -f

      # Koneksi SSH menggunakan ProxyCommand melalui Cloudflare Tunnel
      - name: SSH and Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

        run: |
          ssh -o "ProxyCommand=cloudflared access ssh --hostname $SSH_HOST" -o "StrictHostKeyChecking=no" $SSH_USER@$SSH_HOST << EOF
              # Masuk ke direktori proyek
              cd matrix-calculator
              git config --global url."https://$GH_TOKEN@github.com/".insteadOf "https://github.com/"
              git fetch origin main
              git pull origin main

              pm2 stop backend
              pm2 stop frontend
              cd backend
              source venv/bin/activate
              pip install -r requirements.txt
              
              cd ..

              cd frontend
              npm install
              npm update
              npm run build
              
              pm2 start backend
              pm2 start frontend
          EOF
